DROP TABLE `myTable`;

CREATE TABLE `myTable` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `email` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `myTable` (`email`) VALUES ("tincidunt@dolorelitpellentesque.edu"),("Sed.malesuada.augue@lacus.co.uk"),("Proin.sed@cursusinhendrerit.ca"),("sed.sem.egestas@faucibus.org"),("pharetra.sed.hendrerit@malesuadavelconvallis.ca"),("tincidunt@loremluctusut.org"),("vitae@turpisnec.ca"),("sed@lobortis.com"),("nec.cursus.a@rutrumloremac.net"),("nec.eleifend@non.ca");
INSERT INTO `myTable` (`email`) VALUES ("faucibus@ut.edu"),("feugiat@idmollisnec.co.uk"),("nec.euismod.in@ipsumcursus.com"),("viverra.Maecenas@enim.com"),("odio@Nuncacsem.edu"),("gravida@blanditNamnulla.org"),("non.lorem.vitae@primis.ca"),("leo@semmolestiesodales.org"),("Donec.at.arcu@eleifendnuncrisus.edu"),("Proin.vel.arcu@orciUt.net");
INSERT INTO `myTable` (`email`) VALUES ("nunc.nulla.vulputate@mauris.edu"),("nec.imperdiet.nec@nonbibendumsed.org"),("vel.venenatis.vel@ultricessit.net"),("iaculis.odio@diamDuis.com"),("ullamcorper@malesuada.org"),("ut@purus.com"),("Proin.nisl.sem@nonbibendum.com"),("gravida.sit.amet@Duissitamet.com"),("nunc@pharetra.edu"),("mattis.ornare.lectus@semperauctorMauris.com");
INSERT INTO `myTable` (`email`) VALUES ("nisi.a.odio@vulputate.ca"),("taciti.sociosqu.ad@nasceturridiculusmus.co.uk"),("erat.Etiam.vestibulum@elit.edu"),("at.auctor@eunulla.edu"),("interdum@nequenonquam.co.uk"),("rhoncus.Proin.nisl@laoreet.com"),("Sed.auctor@magnisdisparturient.ca"),("molestie.arcu.Sed@velit.org"),("ultricies.adipiscing@nec.net"),("eu.ultrices.sit@interdumenim.com");
INSERT INTO `myTable` (`email`) VALUES ("blandit.Nam@egestasFusce.co.uk"),("arcu.iaculis.enim@tellusSuspendissesed.com"),("facilisis.facilisis@aliquet.ca"),("nec.mauris@liberoIntegerin.org"),("ultricies.ligula@mollisDuissit.edu"),("urna@vitaealiquetnec.com"),("Nunc.quis.arcu@magnaPhasellus.org"),("varius.ultrices.mauris@necorciDonec.net"),("sapien.gravida.non@sed.com"),("imperdiet.erat.nonummy@facilisisvitaeorci.edu");
INSERT INTO `myTable` (`email`) VALUES ("mauris@egestasSedpharetra.com"),("eget.lacus.Mauris@ac.co.uk"),("nec.metus@fermentumvel.net"),("consectetuer.euismod.est@In.com"),("velit@nibh.org"),("Donec.nibh@dolordolortempus.co.uk"),("fames.ac.turpis@cursusluctus.net"),("Sed@posuerevulputate.co.uk"),("molestie.arcu.Sed@nonnisiAenean.edu"),("magna@miacmattis.org");
INSERT INTO `myTable` (`email`) VALUES ("ornare.libero@vitaealiquameros.co.uk"),("orci.tincidunt@sollicitudincommodoipsum.org"),("id.erat@sed.com"),("facilisis.lorem.tristique@Namporttitor.com"),("Mauris.ut@non.net"),("metus@egestaslaciniaSed.ca"),("sodales@nunc.org"),("augue@Donec.co.uk"),("vehicula@ipsumcursusvestibulum.org"),("Mauris.non@doloregestas.co.uk");
INSERT INTO `myTable` (`email`) VALUES ("lacinia.at.iaculis@Duis.ca"),("enim@lobortisnisi.com"),("dictum@ornareplaceratorci.co.uk"),("Nulla.semper.tellus@et.co.uk"),("tempus.mauris@iaculisodioNam.co.uk"),("lorem.lorem.luctus@Suspendisseeleifend.ca"),("ornare.In.faucibus@lobortis.com"),("libero.Integer.in@sitamet.edu"),("ac.orci.Ut@temporest.ca"),("pellentesque@vehiculaetrutrum.com");
INSERT INTO `myTable` (`email`) VALUES ("montes.nascetur.ridiculus@justositamet.net"),("eget@facilisis.org"),("ligula.Aenean.euismod@lobortis.edu"),("aliquet@ornaretortor.edu"),("dictum@tinciduntcongue.ca"),("elit.Nulla@lobortistellusjusto.co.uk"),("nulla.Donec.non@eleifendvitae.ca"),("dolor@fringillaest.ca"),("felis@odiosemper.org"),("nisl@Cumsociis.net");
INSERT INTO `myTable` (`email`) VALUES ("pharetra.Nam@consequatdolorvitae.co.uk"),("Fusce@nonnisi.com"),("et.magnis@liberoat.org"),("nibh.Phasellus.nulla@interdumliberodui.ca"),("luctus@nonlobortis.net"),("libero@Nullamscelerisque.edu"),("erat.Etiam.vestibulum@leoMorbi.ca"),("nec.metus@Quisqueimperdieterat.ca"),("at.lacus.Quisque@auctorullamcorpernisl.ca"),("eu@eu.co.uk");
