/*sample-data cars*/


INSERT INTO 'mytable' ('year','make','model') VALUES(2012, 'Lexus', 'LS'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2000, 'Audi', 'A8'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2005, 'Mazda', 'Tribute'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2007, 'Honda', 'CR-V'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1970, 'Chevrolet', 'Corvette'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1998, 'Mercedes-Benz', 'E-Class'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1992, 'Honda', 'Prelude'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1997, 'Isuzu', 'Hombre Space'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1997, 'Ford', 'Probe'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2002, 'Chrysler', 'Town & Country'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Ford', 'Probe'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2010, 'Chevrolet', 'Impala'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2001, 'Mercury', 'Sable'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1988, 'Audi', '80/90'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2006, 'Maserati', 'Gran Sport'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2002, 'Saab', '9-3'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1992, 'Oldsmobile', 'Custom Cruiser'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2009, 'Ford', 'E150'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2009, 'Volvo', 'S40'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1996, 'Lexus', 'SC'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2009, 'Subaru', 'Tribeca'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1992, 'Ford', 'Escort'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1957, 'Chevrolet', 'Corvette'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1991, 'Mercury', 'Sable'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2010, 'Jaguar', 'XK'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2000, 'Toyota', 'Corolla'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2008, 'Suzuki', 'Daewoo Lacetti'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2001, 'Lotus', 'Esprit'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2006, 'Mazda', 'Mazda3'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1999, 'Mercury', 'Sable'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1996, 'Audi', 'A4'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1985, 'Pontiac', 'Grand Prix'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2006, 'GMC', 'Yukon XL 2500'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2006, 'BMW', '760'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Mazda', '626'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2005, 'Chrysler', 'Sebring'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2005, 'Panoz', 'Esperante'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1997, 'Nissan', 'Maxima'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1998, 'Pontiac', 'Grand Prix'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2003, 'Porsche', '911'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2011, 'Aston Martin', 'V8 Vantage'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2007, 'Audi', 'RS4'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2011, 'Toyota', 'Venza'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1995, 'Geo', 'Metro'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2002, 'Lincoln', 'Navigator'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2000, 'HUMMER', 'H1'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2002, 'Audi', 'A6'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2006, 'Saturn', 'Ion'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2003, 'Mercedes-Benz', 'S-Class'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2003, 'Volvo', 'V70'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Cadillac', 'Sixty Special'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2000, 'Chevrolet', 'Suburban 2500'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2000, 'Jaguar', 'XK Series'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1991, 'Ford', 'Tempo'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2007, 'Audi', 'Q7'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2010, 'Suzuki', 'Equator'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1992, 'Mitsubishi', 'Mirage'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2004, 'Land Rover', 'Discovery'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2004, 'Toyota', 'Tacoma Xtra'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2007, 'Toyota', 'Tundra'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2011, 'Honda', 'Fit'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Buick', 'Coachbuilder'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1997, 'Volvo', '850'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2004, 'Chevrolet', 'Cavalier'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2013, 'Hyundai', 'Sonata'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2003, 'Lexus', 'LS'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2005, 'Mercedes-Benz', 'S-Class'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2001, 'Acura', 'MDX'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1985, 'Dodge', 'Caravan'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2005, 'Pontiac', 'Monterey'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2001, 'GMC', 'Sierra 2500'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2010, 'Nissan', 'Maxima'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2004, 'Toyota', 'Avalon'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2000, 'Ford', 'Econoline E150'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2002, 'Jaguar', 'XJ Series'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1994, 'Chevrolet', 'Cavalier'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2010, 'Hyundai', 'Tucson'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2007, 'Spyker Cars', 'C8'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Ford', 'Escort'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1985, 'Ford', 'Mustang'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1992, 'GMC', 'Suburban 2500'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2011, 'Toyota', '4Runner'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2000, 'Lotus', 'Esprit'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1994, 'Oldsmobile', 'Achieva'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2001, 'Ford', 'Crown Victoria'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2001, 'Chevrolet', 'Tracker'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Mercedes-Benz', '300E'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2008, 'Chevrolet', 'Cobalt'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2012, 'Mitsubishi', 'Lancer'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2002, 'Saturn', 'VUE'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1996, 'Holden', 'VS Commodore'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2003, 'Ford', 'Escort ZX2'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2008, 'Mercedes-Benz', 'R-Class'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2010, 'Land Rover', 'Freelander'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1995, 'Chevrolet', 'Beretta'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2002, 'Mitsubishi', 'Montero Sport'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Mitsubishi', 'Mirage'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1995, 'Mercury', 'Sable'),
INSERT INTO 'mytable' ('year','make','model') VALUES(1993, 'Dodge', 'Intrepid'),
INSERT INTO 'mytable' ('year','make','model') VALUES(2008, 'Kia', 'Rondo'),